name: minify
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install lua
        uses: xpol/setup-lua@v0.3
      - name: minify
        run: lua .github/minify.lua minify stormui.lua > minified.lua
      - name: Set identity
        run: |
          git config user.email "bot@example.com"
          git config user.name "Minification bot"
      - name: Commit and push
        if: github.event_name == 'push'
        run: |
          git add minified.lua
          git commit -m "Minified script"
          git push
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: minified-script
          path: minified.lua
